version: '3'

tasks:
  run:
    vars:
      YEAR: '{{default "" .YEAR}}'
      DAY: '{{default "" .DAY}}'
      PART: '{{default "" .PART}}'
      LANGUAGE: '{{default "" .LANGUAGE}}'
    cmds:
      - go generate ./languages/go/cmd/advent
      - >
        go run ./cmd/run
        {{- if .YEAR}} --year {{.YEAR}}{{end -}}
        {{- if .DAY}} --day {{.DAY}}{{end -}}
        {{- if .PART}} --part {{.PART}}{{end -}}
        {{- if .LANGUAGE}} --lang {{.LANGUAGE}}{{end -}}
    desc: "Run Advent of Code solutions (use YEAR=/DAY=/PART=/LANGUAGE= variables)"

  go:lint:
    cmds:
      - cd languages/go && golangci-lint run --config .golangci-lint.yaml

  new-day:
    desc: "Scaffold a new day from templates (usage: task new-day YEAR=2024 DAY=12 [LANGUAGE=go])"
    silent: true
    vars:
      YEAR: '{{.YEAR}}'
      DAY: '{{.DAY}}'
      LANGUAGE: '{{default "go" .LANGUAGE}}'
    cmds:
      - |
        set -euo pipefail
        if [ -z "{{.YEAR}}" ] || [ -z "{{.DAY}}" ]; then
          echo "error: provide YEAR and DAY (e.g. task new-day YEAR=2024 DAY=12 LANGUAGE=go)"
          exit 1
        fi
        go run ./cmd/newday --year {{.YEAR}} --day {{.DAY}} --lang {{.LANGUAGE}}
