version: '3'

tasks:
  run:
    cmds:
      - go generate ./languages/go/cmd/advent
      - go run ./cmd/run {{.CLI_ARGS}}
    desc: Run Advent of Code solutions (use --year/--day/--part/--lang flags after --)

  go:lint:
    cmds:
      - cd languages/go && golangci-lint run --config .golangci-lint.yaml --show-stats
