version: '3'

tasks:
  run:
    cmds:
      - task: run:go {{.CLI_ARGS}}

  run:go:
    cmds:
      - go run go/cmd/advent/main.go {{.CLI_ARGS}}

  go:lint:
    cmds:
      - cd go && golangci-lint run  --config .golangci-lint.yaml --show-stats