// Code generated by go generate; DO NOT EDIT.
package main

import (
	y2022d01 "github.com/kellen-miller/aoc/2022/go/day1"
	y2022d02 "github.com/kellen-miller/aoc/2022/go/day2"
	y2022d03 "github.com/kellen-miller/aoc/2022/go/day3"
	y2022d04 "github.com/kellen-miller/aoc/2022/go/day4"
	y2022d05 "github.com/kellen-miller/aoc/2022/go/day5"
	y2022d06 "github.com/kellen-miller/aoc/2022/go/day6"
	y2023d01 "github.com/kellen-miller/aoc/2023/go/day1"
	y2023d02 "github.com/kellen-miller/aoc/2023/go/day2"
	y2023d03 "github.com/kellen-miller/aoc/2023/go/day3"
	y2024d01 "github.com/kellen-miller/aoc/2024/go/day1"
	y2024d10 "github.com/kellen-miller/aoc/2024/go/day10"
	y2024d11 "github.com/kellen-miller/aoc/2024/go/day11"
	y2024d02 "github.com/kellen-miller/aoc/2024/go/day2"
	y2024d03 "github.com/kellen-miller/aoc/2024/go/day3"
	y2024d04 "github.com/kellen-miller/aoc/2024/go/day4"
	y2024d05 "github.com/kellen-miller/aoc/2024/go/day5"
	y2024d06 "github.com/kellen-miller/aoc/2024/go/day6"
	y2024d07 "github.com/kellen-miller/aoc/2024/go/day7"
	y2024d08 "github.com/kellen-miller/aoc/2024/go/day8"
	y2024d09 "github.com/kellen-miller/aoc/2024/go/day9"
	y2025d01 "github.com/kellen-miller/aoc/2025/go/day1"
)

var solutionIndex = map[int]map[int]dayRunners{
	2022: {
		1: {
			Part1: y2022d01.Part1,
			Part2: y2022d01.Part2,
		},
		2: {
			Part1: y2022d02.Part1,
			Part2: y2022d02.Part2,
		},
		3: {
			Part1: y2022d03.Part1,
			Part2: y2022d03.Part2,
		},
		4: {
			Part1: y2022d04.Part1,
			Part2: y2022d04.Part2,
		},
		5: {
			Part1: y2022d05.Part1,
			Part2: y2022d05.Part2,
		},
		6: {
			Part1: y2022d06.Part1,
			Part2: y2022d06.Part2,
		},
	},
	2023: {
		1: {
			Part1: y2023d01.Part1,
			Part2: y2023d01.Part2,
		},
		2: {
			Part1: y2023d02.Part1,
			Part2: y2023d02.Part2,
		},
		3: {
			Part1: y2023d03.Part1,
			Part2: y2023d03.Part2,
		},
	},
	2024: {
		1: {
			Part1: y2024d01.Part1,
			Part2: y2024d01.Part2,
		},
		2: {
			Part1: y2024d02.Part1,
			Part2: y2024d02.Part2,
		},
		3: {
			Part1: y2024d03.Part1,
			Part2: y2024d03.Part2,
		},
		4: {
			Part1: y2024d04.Part1,
			Part2: y2024d04.Part2,
		},
		5: {
			Part1: y2024d05.Part1,
			Part2: y2024d05.Part2,
		},
		6: {
			Part1: y2024d06.Part1,
			Part2: y2024d06.Part2,
		},
		7: {
			Part1: y2024d07.Part1,
			Part2: y2024d07.Part2,
		},
		8: {
			Part1: y2024d08.Part1,
			Part2: y2024d08.Part2,
		},
		9: {
			Part1: y2024d09.Part1,
			Part2: y2024d09.Part2,
		},
		10: {
			Part1: y2024d10.Part1,
			Part2: y2024d10.Part2,
		},
		11: {
			Part1: y2024d11.Part1,
			Part2: y2024d11.Part2,
		},
	},
	2025: {
		1: {
			Part1: y2025d01.Part1,
			Part2: y2025d01.Part2,
		},
	},
}
